### ISSUE TITLE
search link to "TELEPHONE MUSIC -- TODD LEREW -- online correspondence, ," broken

### ISSUE THREAD

**Issue by whatcoloris** [emergencyindex/emergencyindex.com#20] opened 2019-03-23 20:39 UTC
this link in the auto-complete is broken, possibly because of the random commas? it's 2011:028-029

ugh

**Comment by whatcoloris** [comment] 2019-03-23 20:39
works fine in volume view, but when searching it just sits there.

**Comment by edwardsharp** [comment] 2019-03-23 21:09
woooo, this is a really great find!!! 

i'm working on moving to Materialize v1 and re-factoring all of the javascript to remove jQuery. 

the problem is that `onAutocomplete` does this: `hrefObj[val+'HREF']` which doesn't account for the val string getting it's whitespace trimmed. i fixed this by filtering the `hrefObj` keys with a `.match()` like: 
```js 
Object.keys(hrefObj).filter(function(i){return i.match(val)})[0]
```

anyhow, will get a PR for all this soon

**Closed as completed** 2019-03-25 13:37 UTC
